#!/bin/bash

#set -x
. settings/general

PROFILE_NAME=$1
PROFILE=${PROFILES}/${PROFILE_NAME}
[ ! -f ${PROFILE} ] && echo "Couldn't fine ${PROFILE}, exiting" && exit 1
. ${PROFILE}

function run_486 {
  MACHINE=${1:-ct486}

  ### GENERAL OPTIONS
  OPTIONS="-skip_gameinfo -isa1 ${VGA} -isa2 ${SND} -ramsize ${RAMSIZE}"

  ### FLOPPIES
  [ ! -z "${FLOP1}" ] && OPTIONS+=" -flop1 ${FLOPPATH}/${FLOP1}"
  [ ! -z "${FLOP2}" ] && OPTIONS+=" -flop2 ${FLOPPATH}/${FLOP2}"

  #### HARD DISK
  [ ! -z "${HARD1}" ] && OPTIONS+=" -board3:ide:ide:0 hdd -harddisk ${HDDPATH}/${HARD1}"
  [ ! -z "${HARD2}" ] && OPTIONS+=" -board3:ide:ide:1 hdd -harddisk ${HDDPATH}/${HARD2}"
  [ ! -z "${SCSIH1}" ] && OPTIONS+=" -isa3 aha1542a -isa3:aha1542a:scsi:0 harddisk -harddisk ${HDDPATH}/${SCSIH1}"

  #### CDROM
  [ ! -z "${CDROM}" ] && OPTIONS+=" -board3:ide:ide:1 cdrom -cdrom ${CDPATH}/${CDROM}"
  [ ! -z "${PXCD}" ] && OPTIONS+=" -board3:ide:ide:1 px320a -cdrom ${CDPATH}/${PXCD}"
  [ ! -z "${ECDROM}" ] && OPTIONS+=" -isa3 ide -isa3:ide:ide:0 cdrom -cdrom ${CDPATH}/${ECDROM}"
  [ ! -z "${SCSICD}" ] && OPTIONS+=" -isa3 aha1542a -isa3:aha1542a:scsi:6 cdrom -cdrom ${CDPATH}/${SCSICD}"

  #### NETWORK
  [ ! -z "${NETWORK}" ] && OPTIONS+=" -isa4 ${NETWORK}"

  #### SERIAL
  [ ! -z "${SERIAL}" ] && OPTIONS+=" -board2:comat:serport0 ${SERIAL}"
  [ ! -z "${SERIAL}" ] && OPTIONS+=" -board2:comat:serport1 logitech_mouse"
  [ ! -z "${BITB}" ] && OPTIONS+=" -bitb ${BITB}"
  
  ### using the isa ide card results in hdd controller failure in bios
  #[ ! -z "${CDROM}" ] && OPTIONS+=" -isa3 ide -isa3:ide:ide:0 cdrom -cdrom ${CDPATH}/${CDROM}"

  #### NVRAM
  NVRAM_PROFILE=${NVRAMPATH}/${PROFILE_NAME}
  [ ! -d ${NVRAM_PROFILE} ] && mkdir ${NVRAM_PROFILE}
  OPTIONS+=" -nvram_directory ${NVRAM_PROFILE}"

  cd ${MAMEBASE}
  #./mame-modded ${MACHINE} ${OPTIONS}
  ./mame ${MACHINE} ${OPTIONS}
}
