#!/bin/bash

HARD1=$HOME/games/emulator-mame/_local/test/disk.chd
INST="$HOME/games/emulator-mame/_local/floppies/amiga/367943-01_install.adf"
MODEM=127.0.0.1
VGA=svga_s3
SND=sblaster_16
PORT=${1:-25232}


function run {
./mame64 a600 \
  -skip_gameinfo \
  -hard1 "${HARD1}"
#  -flop1 "${INST}"
}


run
