#!/bin/bash

RAMSIZE=64m
# CYLS:256,HEADS:16,SECS:50,BPS:512
#HARD1=$HOME/games/emulator-mame/_local/hdd/msdos622_100mb_288.chd
HARD1=$HOME/games/emulator-mame/_local/test/disk.chd
#HARD1=$HOME/games/emulator-mame/_local/test/msdos622_100mb_288.chd
HARD2=$HOME/games/emulator-mame/_local/hdd/renegadebbs_100mb.chd
CDROM=$HOME/games/emulator-mame/_local/cdrom/fdbootcd.iso
DOSINST="$HOME/games/emulator-mame/_local/floppies/MS-DOS 6.22 Disk 1 Setup.IMA"
#DOSINST="$HOME/games/emulator-mame/_local/floppies/win98boot.ima"
#FLOP1=$HOME/games/emulator-mame/_local/floppies/Dos6.22.img
MODEM=127.0.0.1
VGA=svga_s3
SND=sblaster_16
PORT=${1:-25232}


#  -flop1 "${DOSINST}"  \
function run_bbs {
./mame64 ct486 \
  -skip_gameinfo \
  -board3:ide:ide:0 hdd \
  -hard1 "${HARD1}" \
  -board3:ide:ide:1 hdd \
  -hard2 "${HARD2}" \
  -isa1 ${VGA} \
  -isa2 ${SND} \
  -ramsize $RAMSIZE \
  -board2:comat:serport1 null_modem \
  -bitb socket.${MODEM}:25232
#  -isa3 comat \
#  -isa3:comat:serport0 null_modem
#  -bitb3 socket.${MODEM}:25234 \
#  -isa3:comat:serport1 null_modem \
#  -bitb4 socket.${MODEM}:25235 \
#  -isa4 ide \
#  -isa4:ide:ide:0 cdrom \
#  -cdrom "${CDROM}"
}


run_bbs 
#run_bbs 25233 1 1
